<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>mDiscover.ViewModels</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mDiscover.Core\mDiscover.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

</Project>
