<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>mDiscover.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mDiscover.Core\mDiscover.Core.csproj" />
    <ProjectReference Include="..\mDiscover.ViewModels\mDiscover.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
  </ItemGroup>

</Project>

